#!/bin/bash
#SBATCH --partition=gpu-single
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=6
#SBATCH --gres=gpu:A40:1
#SBATCH --time=24:00:00
#SBATCH --mem=6gb
#SBATCH --output=/home/hd/hd_hd/hd_dn249/ConformalAutoencoder/Cluster/output/%j.out
module load devel/miniforge
conda activate confAE

python ../CelebA/train_model.py  --z_dim 256 --lambda_conf 1.0 --lambda_reg 0.001 --path models/conformal_autoencoder_v1_3 --bs 512 --steps 400 --recon_loss mse --val_every 40
python ../CelebA/train_model.py  --z_dim 512 --lambda_conf 1.0 --lambda_reg 0.001 --path models/conformal_autoencoder_v1_4 --bs 512 --steps 400 --recon_loss mse --val_every 40
python ../CelebA/train_model.py  --z_dim 1024 --lambda_conf 1.0 --lambda_reg 0.001 --path models/conformal_autoencoder_v1_5 --bs 512 --steps 400 --recon_loss mse --val_every 40